#!/usr/bin/env python3
"""scripts/potatofy.py

Waits for EVE's core_public__.yaml to appear, then overwrites it with
an "Ultra Lite" (potato) settings profile.

Designed to be run on the Debian Zombie host (192.168.14.105) while the
client is booting for the very first time.

Usage examples:
  python3 scripts/potatofy.py --root ~/ --timeout 1800
  python3 scripts/potatofy.py --file /path/to/core_public__.yaml

Notes:
- We intentionally *overwrite* the file rather than trying to merge.
- The format here is a minimal YAML mapping (EVE settings readers are tolerant).
"""

from __future__ import annotations

import argparse
import hashlib
import os
import sys
import time
from pathlib import Path


POTATO_YAML = """# Autogenerated by scripts/potatofy.py
# Ultra Lite / Zombie graphics profile
WindowMode: 1
textureQuality: 0
shaderQuality: 0
shadowQuality: 0
antiAliasing: 0
"""


def _iter_candidate_paths(root: Path) -> list[Path]:
    candidates: list[Path] = []

    # Common-ish EVE settings location pattern:
    # .../CCP/EVE/.../settings_Default/core_public__.yaml
    for path in root.rglob("core_public__.yaml"):
        if "settings_Default" in str(path) and "CCP" in str(path) and "EVE" in str(path):
            candidates.append(path)

    # Fallback: any core_public__.yaml under the root.
    if not candidates:
        candidates = list(root.rglob("core_public__.yaml"))

    return candidates


def _write_atomically(target: Path, content: str) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    tmp = target.with_suffix(target.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    os.replace(tmp, target)


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser(description="Wait for core_public__.yaml then overwrite with Ultra Lite settings")
    parser.add_argument(
        "--root",
        default=str(Path.home()),
        help="Directory to search under (default: user home)",
    )
    parser.add_argument(
        "--file",
        default=None,
        help="Explicit path to core_public__.yaml (skips search)",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=1800,
        help="Seconds to wait before failing (default: 1800)",
    )
    parser.add_argument(
        "--poll",
        type=float,
        default=2.0,
        help="Seconds between polls (default: 2.0)",
    )
    parser.add_argument(
        "--enable-3d-key",
        action="store_true",
        help="Also write '3dEnabled: false' if you want it included.",
    )

    args = parser.parse_args()

    content = POTATO_YAML
    if args.enable_3d_key:
        content += "3dEnabled: false\n"

    desired_hash = _sha256_text(content)

    deadline = time.time() + args.timeout

    explicit_file = Path(args.file).expanduser() if args.file else None
    if explicit_file:
        print(f"[*] Enforcing core_public__.yaml at: {explicit_file}")
        last_status_ts = 0.0

        while time.time() < deadline:
            if explicit_file.exists():
                try:
                    current_hash = _sha256_file(explicit_file)
                except Exception:
                    current_hash = ""

                if current_hash != desired_hash:
                    _write_atomically(explicit_file, content)
                    print("[SUCCESS] Overwrote core_public__.yaml with Ultra Lite settings.")
                    print(f"[ok] Wrote Ultra Lite settings to: {explicit_file}")
                else:
                    if (time.time() - last_status_ts) > 300:
                        print("[ok] core_public__.yaml already Ultra Lite; monitoring...")
                        last_status_ts = time.time()

            time.sleep(args.poll)

        print(f"[err] Timed out waiting for: {explicit_file}", file=sys.stderr)
        return 2

    root = Path(args.root).expanduser()
    print(f"[*] Waiting for core_public__.yaml under: {root}")

    target: Path | None = None
    last_status_ts = 0.0

    while time.time() < deadline:
        if not root.exists():
            time.sleep(args.poll)
            continue

        if target is None:
            matches = _iter_candidate_paths(root)
            if matches:
                # Prefer deepest path (usually indicates actual settings tree)
                matches.sort(key=lambda p: len(str(p)), reverse=True)
                target = matches[0]
                print(f"[ok] Found core_public__.yaml candidate: {target}")

        if target is not None:
            if target.exists():
                try:
                    current_hash = _sha256_file(target)
                except Exception:
                    current_hash = ""

                if current_hash != desired_hash:
                    _write_atomically(target, content)
                    print("[SUCCESS] Overwrote core_public__.yaml with Ultra Lite settings.")
                    print(f"[ok] Wrote Ultra Lite settings to: {target}")
                else:
                    if (time.time() - last_status_ts) > 300:
                        print("[ok] core_public__.yaml already Ultra Lite; monitoring...")
                        last_status_ts = time.time()
            else:
                # If the settings path changes (launcher rotates folders), rediscover.
                target = None

        time.sleep(args.poll)

    print("[err] Timed out waiting for core_public__.yaml", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
